# Generated by Django 5.1.15 on 2026-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('clients', '0002_initial'),
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTrasporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('anno', models.PositiveIntegerField()),
                ('data_documento', models.DateField()),
                ('ora_inizio_trasporto', models.TimeField(blank=True, null=True)),
                ('causale_trasporto', models.CharField(choices=[('VENDITA', 'Vendita'), ('CONTO_VISIONE', 'Conto visione/prova'), ('CONTO_LAVORAZIONE', 'Conto lavorazione'), ('RESO', 'Reso'), ('TRASFERIMENTO', 'Trasferimento tra sedi'), ('RIPARAZIONE', 'Riparazione/assistenza tecnica')], default='VENDITA', max_length=20)),
                ('aspetto_beni', models.CharField(choices=[('COLLI', 'A colli'), ('SFUSO', 'Sfuso'), ('PALLET', 'Pallet')], default='COLLI', max_length=10)),
                ('numero_colli', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porto', models.CharField(choices=[('FRANCO', 'Franco (mittente)'), ('ASSEGNATO', 'Assegnato (destinatario)')], default='FRANCO', max_length=10)),
                ('vettore', models.CharField(blank=True, max_length=255)),
                ('fatturato', models.BooleanField(default=False, help_text='True quando confluito in una fattura differita')),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddt', to='clients.anagrafica')),
                ('indirizzo_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ddt', to='clients.indirizzospedizione')),
                ('magazzino_partenza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddt_partenza', to='warehouse.magazzino')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Documento di trasporto (DDT)',
                'verbose_name_plural': 'Documenti di trasporto (DDT)',
                'ordering': ['-anno', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RigaDDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.PositiveIntegerField()),
                ('descrizione', models.CharField(blank=True, help_text="Se vuota, si usa la descrizione dell'articolo", max_length=255)),
                ('quantita', models.DecimalField(decimal_places=3, max_digits=14)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.articolo')),
                ('ddt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='ddt.documentotrasporto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Riga DDT',
                'verbose_name_plural': 'Righe DDT',
                'ordering': ['numero_riga'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentotrasporto',
            constraint=models.UniqueConstraint(fields=('tenant', 'anno', 'numero'), name='unique_numero_ddt_per_tenant_anno'),
        ),
        migrations.AddConstraint(
            model_name='rigaddt',
            constraint=models.UniqueConstraint(fields=('ddt', 'numero_riga'), name='unique_numero_riga_per_ddt'),
        ),
    ]
