# Generated by Django 5.1.15 on 2026-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('core', '0002_contatore'),
        ('ddt', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentotrasporto',
            name='unique_numero_ddt_per_tenant_anno',
        ),
        migrations.AddField(
            model_name='documentotrasporto',
            name='confermato',
            field=models.BooleanField(default=False, help_text="True dopo l'emissione: numero assegnato e magazzino scaricato. Una bozza (False) puo' essere modificata liberamente, un DDT confermato no."),
        ),
        migrations.AlterField(
            model_name='documentotrasporto',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text='Lasciare vuoto in bozza: viene assegnato automaticamente alla conferma', null=True),
        ),
        migrations.AddConstraint(
            model_name='documentotrasporto',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('tenant', 'anno', 'numero'), name='unique_numero_ddt_per_tenant_anno'),
        ),
    ]
