# Generated by Django 5.1.15 on 2026-08-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_contatore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ARUBA', 'Aruba Fatturazione Elettronica'), ('OPENAPI', 'OpenAPI.it'), ('FATTURE_IN_CLOUD', 'Fatture in Cloud'), ('ALTRO', 'Altro provider / integrazione personalizzata')], max_length=30)),
                ('api_base_url', models.URLField(blank=True, help_text='Endpoint API del provider, se diverso da quello di default per il provider scelto')),
                ('api_key_cifrata', models.TextField(blank=True)),
                ('client_id_cifrato', models.TextField(blank=True)),
                ('client_secret_cifrato', models.TextField(blank=True)),
                ('username_cifrato', models.TextField(blank=True)),
                ('password_cifrata', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, help_text='Es. numero di contratto, referente del provider, promemoria vari')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Configurazione SDI',
                'verbose_name_plural': 'Configurazioni SDI',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_configurazione_sdi_per_tenant')],
            },
        ),
    ]
