# Generated by Django 5.1.15 on 2026-08-31 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(help_text="es. 'DDT', 'PREVENTIVO', 'ORDINE_CLIENTE'", max_length=50)),
                ('anno', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Contatore di numerazione',
                'verbose_name_plural': 'Contatori di numerazione',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'chiave', 'anno'), name='unique_contatore_per_tenant_chiave_anno')],
            },
        ),
    ]
