# Generated by Django 5.1.15 on 2026-09-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='colore_accento',
            field=models.CharField(default='#1f1a17', help_text="Colore in formato esadecimale, es. #1f1a17, usato nell'intestazione dei documenti PDF", max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='iban',
            field=models.CharField(blank=True, help_text="Mostrato come modalita' di pagamento in fatture e XML", max_length=34),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='loghi_aziende/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='piede_pagina_legale',
            field=models.TextField(blank=True, help_text='Testo libero stampato in fondo a fatture/DDT/documenti, es. capitale sociale, numero REA, tribunale competente'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='regime_fiscale',
            field=models.CharField(default='RF01', help_text="Codice regime fiscale per la fattura elettronica. Il piu' comune e' RF01 (ordinario); RF19 e' il regime forfettario. Altri codici: consulta il tuo commercialista se necessario.", max_length=4),
        ),
    ]
