# Generated by Django 5.1.15 on 2026-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_colore_accento_tenant_iban_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='giorni_attesa_invio_sdi',
            field=models.PositiveIntegerField(default=3, help_text="Giorni di attesa dopo l'emissione di una fattura prima dell'invio automatico a SDI. 0 = nessuna attesa (il task schedulato la invia al primo giro utile). L'azione manuale 'Invia a SDI' resta comunque disponibile per inviare subito."),
        ),
    ]
