# Generated by Django 5.1.15 on 2026-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('predefinito', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Magazzino',
                'verbose_name_plural': 'Magazzini',
            },
        ),
        migrations.CreateModel(
            name='MovimentoMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causale', models.CharField(choices=[('CARICO_ACQUISTO', 'Carico da acquisto'), ('CARICO_RESO_CLIENTE', 'Carico da reso cliente'), ('CARICO_RETTIFICA', 'Rettifica di inventario (carico)'), ('SCARICO_VENDITA', 'Scarico per vendita/DDT'), ('SCARICO_RESO_FORNITORE', 'Scarico per reso a fornitore'), ('SCARICO_RETTIFICA', 'Rettifica di inventario (scarico)'), ('TRASFERIMENTO', 'Trasferimento tra magazzini')], max_length=30)),
                ('quantita', models.DecimalField(decimal_places=3, help_text='Positiva per i carichi, negativa per gli scarichi', max_digits=14)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('documento_riferimento', models.CharField(blank=True, help_text="es. 'DDT 2026/145' o 'Fattura 2026/302', per tracciabilita' rapida", max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='catalog.articolo')),
                ('magazzino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='warehouse.magazzino')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Movimento di magazzino',
                'verbose_name_plural': 'Movimenti di magazzino',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Giacenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giacenze', to='catalog.articolo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('magazzino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giacenze', to='warehouse.magazzino')),
            ],
            options={
                'verbose_name': 'Giacenza',
                'verbose_name_plural': 'Giacenze',
                'constraints': [models.UniqueConstraint(fields=('magazzino', 'articolo'), name='unique_giacenza_magazzino_articolo')],
            },
        ),
    ]
