# Generated by Django 5.1.15 on 2026-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cliente', models.BooleanField(default=True)),
                ('is_fornitore', models.BooleanField(default=False)),
                ('tipo_soggetto', models.CharField(choices=[('PF', 'Persona fisica'), ('PG', 'Persona giuridica')], default='PG', max_length=2)),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('partita_iva', models.CharField(blank=True, max_length=11)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('codice_destinatario_sdi', models.CharField(blank=True, default='0000000', max_length=7)),
                ('pec_fatturazione', models.EmailField(blank=True, max_length=254)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('nazione', models.CharField(default='IT', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anagrafica cliente/fornitore',
                'verbose_name_plural': 'Anagrafiche clienti/fornitori',
            },
        ),
        migrations.CreateModel(
            name='IndirizzoSpedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, help_text="es. 'Magazzino nord'", max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('citta', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
