# Generated by Django 5.1.15 on 2026-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='indirizzospedizione',
            name='anagrafica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi_spedizione', to='clients.anagrafica'),
        ),
        migrations.AddField(
            model_name='indirizzospedizione',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='anagrafica',
            constraint=models.UniqueConstraint(condition=models.Q(('partita_iva', ''), _negated=True), fields=('tenant', 'partita_iva'), name='unique_piva_per_tenant'),
        ),
    ]
