# Generated by Django 5.1.15 on 2026-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoNonFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('ORDINE_CLIENTE', 'Ordine cliente'), ('ORDINE_FORNITORE', 'Ordine fornitore'), ('RICEVUTA', 'Ricevuta di cortesia'), ('RAPPORTINO', 'Rapportino di intervento')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('anno', models.PositiveIntegerField()),
                ('data_documento', models.DateField()),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATO', 'Inviato al destinatario'), ('ACCETTATO', 'Accettato/confermato'), ('RIFIUTATO', 'Rifiutato'), ('CHIUSO', 'Chiuso')], default='BOZZA', max_length=20)),
                ('validita_giorni', models.PositiveIntegerField(blank=True, help_text='Per i preventivi', null=True)),
                ('imponibile', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documenti_non_fiscali', to='clients.anagrafica')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Documento non fiscale',
                'verbose_name_plural': 'Documenti non fiscali',
                'ordering': ['-anno', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RigaDocumentoNonFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.PositiveIntegerField()),
                ('descrizione', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('prezzo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.articolo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='documents.documentononfiscale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Riga documento',
                'verbose_name_plural': 'Righe documento',
                'ordering': ['numero_riga'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentononfiscale',
            constraint=models.UniqueConstraint(fields=('tenant', 'tipo', 'anno', 'numero'), name='unique_numero_doc_per_tenant_tipo_anno'),
        ),
        migrations.AddConstraint(
            model_name='rigadocumentononfiscale',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_riga'), name='unique_numero_riga_per_documento'),
        ),
    ]
