# Generated by Django 5.1.15 on 2026-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('core', '0002_contatore'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentononfiscale',
            name='unique_numero_doc_per_tenant_tipo_anno',
        ),
        migrations.AlterField(
            model_name='documentononfiscale',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text='Lasciare vuoto in bozza: viene assegnato automaticamente alla conferma', null=True),
        ),
        migrations.AddConstraint(
            model_name='documentononfiscale',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('tenant', 'tipo', 'anno', 'numero'), name='unique_numero_doc_per_tenant_tipo_anno'),
        ),
    ]
