# Generated by Django 5.1.15 on 2026-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('clients', '0002_initial'),
        ('core', '0001_initial'),
        ('ddt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieNumerazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='es. FT, NC', max_length=10)),
                ('anno', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Serie di numerazione',
                'verbose_name_plural': 'Serie di numerazione',
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('data_documento', models.DateField()),
                ('tipo_documento_sdi', models.CharField(choices=[('TD01', 'TD01 - Fattura'), ('TD04', 'TD04 - Nota di credito'), ('TD05', 'TD05 - Nota di debito'), ('TD24', 'TD24 - Fattura differita (art. 21 c.4 lett. a)')], default='TD01', max_length=4)),
                ('imponibile', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imposta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stato_sdi', models.CharField(choices=[('BOZZA', 'Bozza'), ('DA_INVIARE', 'Da inviare a SDI'), ('INVIATA', 'Inviata, in attesa di esito'), ('CONSEGNATA', 'Consegnata al destinatario'), ('SCARTATA', 'Scartata da SDI'), ('MANCATA_CONSEGNA', 'Mancata consegna (impegnativa comunque)'), ('NON_FISCALE', 'Documento non inviato a SDI')], default='BOZZA', max_length=20)),
                ('identificativo_sdi', models.CharField(blank=True, help_text="ID assegnato da SDI dopo l'invio", max_length=50)),
                ('xml_fatturapa', models.TextField(blank=True, help_text="XML FatturaPA generato, conservato per l'invio/conservazione")),
                ('ricevuta_sdi', models.TextField(blank=True, help_text='Ultima ricevuta/notifica ricevuta dal provider SDI')),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatture', to='clients.anagrafica')),
                ('ddt_collegati', models.ManyToManyField(blank=True, related_name='fatture', to='ddt.documentotrasporto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatture', to='invoicing.serienumerazione')),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'ordering': ['-data_documento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RigaFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.PositiveIntegerField()),
                ('descrizione', models.CharField(max_length=255)),
                ('quantita', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('prezzo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=22, max_digits=5)),
                ('natura_iva', models.CharField(blank=True, max_length=4)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.articolo')),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='invoicing.fattura')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Riga fattura',
                'verbose_name_plural': 'Righe fattura',
                'ordering': ['numero_riga'],
                'constraints': [models.UniqueConstraint(fields=('fattura', 'numero_riga'), name='unique_numero_riga_per_fattura')],
            },
        ),
        migrations.AddConstraint(
            model_name='serienumerazione',
            constraint=models.UniqueConstraint(fields=('tenant', 'codice', 'anno'), name='unique_serie_per_tenant_anno'),
        ),
        migrations.AddConstraint(
            model_name='fattura',
            constraint=models.UniqueConstraint(fields=('tenant', 'serie', 'numero'), name='unique_numero_fattura_per_serie'),
        ),
    ]
