# Generated by Django 5.1.15 on 2026-08-31 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('core', '0002_contatore'),
        ('ddt', '0002_remove_documentotrasporto_unique_numero_ddt_per_tenant_anno_and_more'),
        ('invoicing', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fattura',
            name='unique_numero_fattura_per_serie',
        ),
        migrations.AddField(
            model_name='fattura',
            name='confermata',
            field=models.BooleanField(default=False, help_text="True dopo l'emissione: numero assegnato e (se immediata) magazzino scaricato"),
        ),
        migrations.AddField(
            model_name='fattura',
            name='magazzino',
            field=models.ForeignKey(blank=True, help_text='Necessario solo per fatture immediate (senza DDT collegati) che contengono beni fisici', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fatture_immediate', to='warehouse.magazzino'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='numero',
            field=models.PositiveIntegerField(blank=True, help_text="Lasciare vuoto in bozza: viene assegnato automaticamente all'emissione", null=True),
        ),
        migrations.AddConstraint(
            model_name='fattura',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('tenant', 'serie', 'numero'), name='unique_numero_fattura_per_serie'),
        ),
    ]
