# Generated by Django 5.1.15 on 2026-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_remove_fattura_unique_numero_fattura_per_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='emesso_il',
            field=models.DateTimeField(blank=True, help_text="Data/ora esatta dell'emissione, usata per calcolare l'invio differito a SDI", null=True),
        ),
    ]
