# Generated by Django 5.1.15 on 2026-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('BENE', 'Bene fisico (gestito a magazzino)'), ('SERVIZIO', 'Servizio (non gestito a magazzino)')], default='BENE', max_length=10)),
                ('unita_misura', models.CharField(default='PZ', max_length=10)),
                ('prezzo_vendita', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=22, help_text='Percentuale IVA applicata (es. 22.00, 10.00, 4.00, 0.00)', max_digits=5)),
                ('natura_iva', models.CharField(blank=True, help_text='Codice natura IVA per fattura elettronica se aliquota 0 (es. N1, N2.1, N3.5...)', max_length=4)),
                ('scorta_minima', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria articolo',
                'verbose_name_plural': 'Categorie articolo',
            },
        ),
    ]
