# Generated by Django 5.1.15 on 2026-08-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='categoriaarticolo',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sottocategorie', to='catalog.categoriaarticolo'),
        ),
        migrations.AddField(
            model_name='categoriaarticolo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='catalog.categoriaarticolo'),
        ),
        migrations.AddConstraint(
            model_name='articolo',
            constraint=models.UniqueConstraint(fields=('tenant', 'codice'), name='unique_codice_articolo_per_tenant'),
        ),
    ]
